### ISSUE TITLE
test data crashes after loading data

### ISSUE THREAD

**Issue by kylemcdonald** [ebattenberg/nmf-cuda#1]
when i run the example command i get one of two results. first:

```
kyle:bionmf-gpu kyle$ bin/NMF_GPU test/ALL_AML_data.txt -k 2 -j 10 -t 40 -i 2000
    <<< NMF-mGPU: Non-negative Matrix Factorization on GPU >>>
                Single-GPU version
Loading input file...
    File selected as ASCII text. Loading...
        Data matrix selected as having numeric column headers: No.
        Data matrix selected as having numeric row labels: No.
        Row labels detected.
        Number of data columns detected (excluding row labels): 38.
        Name (i.e., description string) detected.
        Column headers detected.
        Loaded a 5000 x 38 data matrix (190000 items).
```

and then either:

```
Segmentation fault: 11
```

or

```
NMF_GPU(52045,0x7fff792a8300) malloc: *** error for object 0x7fac94ab4598: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

this is on osx 10.10 / xcode 6.3 / CUDA 7.0 with a single GPU (GeForce GT 750M)

**Comment by ebattenberg** [comment]
I'm not sure what test code you're referring to.

**Comment by kylemcdonald** [comment]
sorry, i should have said "test data" not "test code". i was referring to the `test/ALL_AML_data.txt` data.

at the time i didn't understand how little memory the 750M had, and i wouldn't be surprised if it was just an allocation error sometimes appearing as a segmentation fault?

going to close this since i'm not using the 750M for this sort of thing anymore and won't be able to help test/reproduce this bug.
